version: "3.8"

services:
  nfs-server:
    restart: always
    image: nfs-server-new
    container_name: 'nfs-server'
    privileged: true
    ports:
      - 111:111/tcp
      - 111:111/udp
      - 2049:2049/tcp
      - 2049:2049/udp
      - 20048:20048/tcp
      - 20048:20048/udp
    volumes:
      - ../bvtm:/bvtm
    command: ["/bvtm"]
